// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dynoinc/skyvault/internal/database (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -destination=mock_database.go -package=mocks github.com/dynoinc/skyvault/internal/database Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	database "github.com/dynoinc/skyvault/internal/database"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddL0Batch mocks base method.
func (m *MockQuerier) AddL0Batch(ctx context.Context, path string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddL0Batch", ctx, path)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddL0Batch indicates an expected call of AddL0Batch.
func (mr *MockQuerierMockRecorder) AddL0Batch(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddL0Batch", reflect.TypeOf((*MockQuerier)(nil).AddL0Batch), ctx, path)
}

// GetAllL0Batches mocks base method.
func (m *MockQuerier) GetAllL0Batches(ctx context.Context) ([]database.L0Batch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllL0Batches", ctx)
	ret0, _ := ret[0].([]database.L0Batch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllL0Batches indicates an expected call of GetAllL0Batches.
func (mr *MockQuerierMockRecorder) GetAllL0Batches(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllL0Batches", reflect.TypeOf((*MockQuerier)(nil).GetAllL0Batches), ctx)
}
