// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: l0.sql

package database

import (
	"context"
)

const placeholder = `-- name: placeholder :one
SELECT 1
`

func (q *Queries) placeholder(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholder)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
