// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: l0_batches.sql

package database

import (
	"context"
)

const addL0Batch = `-- name: AddL0Batch :one
INSERT INTO l0_batches (path, size_bytes, min_key, max_key) VALUES ($1, $2, $3, $4) RETURNING id
`

type AddL0BatchParams struct {
	Path      string
	SizeBytes int64
	MinKey    string
	MaxKey    string
}

func (q *Queries) AddL0Batch(ctx context.Context, arg AddL0BatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, addL0Batch,
		arg.Path,
		arg.SizeBytes,
		arg.MinKey,
		arg.MaxKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllL0Batches = `-- name: GetAllL0Batches :many
SELECT id, path, size_bytes, min_key, max_key, status, created_at FROM l0_batches
`

func (q *Queries) GetAllL0Batches(ctx context.Context) ([]L0Batch, error) {
	rows, err := q.db.Query(ctx, getAllL0Batches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []L0Batch
	for rows.Next() {
		var i L0Batch
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.SizeBytes,
			&i.MinKey,
			&i.MaxKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
