// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	v1 "github.com/dynoinc/skyvault/gen/proto/common/v1"
)

type Querier interface {
	AddSharedRun(ctx context.Context, attrs *v1.Run) error
	AddWriteAheadLog(ctx context.Context, attrs *v1.WriteAheadLog) error
	DeleteSharedRuns(ctx context.Context, seqNos []int64) (bool, error)
	DeleteWriteAheadLogs(ctx context.Context, seqNos []int64) (bool, error)
	GetPartitions(ctx context.Context) ([]Partition, error)
	GetSharedRuns(ctx context.Context) ([]SharedRun, error)
	GetWriteAheadLogs(ctx context.Context) ([]WriteAheadLog, error)
	GetWriteAheadLogsToCompact(ctx context.Context) ([]WriteAheadLog, error)
	MarkWriteAheadLogsAsCompacting(ctx context.Context, seqNos []int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
