// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	dto "github.com/dynoinc/skyvault/internal/database/dto"
)

type L0Batch struct {
	SeqNo   int64
	Version int32
	Attrs   dto.L0BatchAttrs
}
