// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	dto "github.com/dynoinc/skyvault/internal/database/dto"
)

type Querier interface {
	AddL0Batch(ctx context.Context, attrs dto.L0BatchAttrs) error
	DeleteL0Batch(ctx context.Context, arg DeleteL0BatchParams) (L0Batch, error)
	GetL0Batches(ctx context.Context) ([]L0Batch, error)
	GetL0BatchesBySeqNo(ctx context.Context, batchSeqNos []int64) ([]L0Batch, error)
	UpdateL0Batch(ctx context.Context, arg UpdateL0BatchParams) (L0Batch, error)
}

var _ Querier = (*Queries)(nil)
