// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	v1 "github.com/dynoinc/skyvault/gen/proto/common/v1"
)

type L0Batch struct {
	SeqNo   int64
	Version int32
	Attrs   *v1.L0Batch
}

type Partition struct {
	InclusiveStartKey string
	Attrs             *v1.Partition
}
