// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type L0Batch struct {
	ID        int64
	Path      string
	SizeBytes int64
	MinKey    string
	MaxKey    string
	Status    *string
	CreatedAt pgtype.Timestamptz
}
