{{- if .Values.batcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-batcher
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: batcher
spec:
  type: NodePort
  ports:
    - port: {{ .Values.batcher.port }}
      targetPort: {{ .Values.batcher.port }}
      protocol: TCP
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: batcher
{{- end }} 