{{- if .Values.batcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-batcher
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: batcher
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: batcher
{{- end }} 