{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-cache
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cache.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
{{- end }} 