{{- if .Values.cache.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyvault.fullname" . }}-cache-{{ .Values.cache.instance }}
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    skyvault.io/instance: {{ .Values.cache.instance }}
spec:
  replicas: {{ .Values.cache.replicas }}
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
      skyvault.io/instance: {{ .Values.cache.instance }}
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
        skyvault.io/instance: {{ .Values.cache.instance }}
    spec:
      serviceAccountName: {{ include "skyvault.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        # Mount ConfigMap as a volume if needed for file-based configuration
        - name: config-volume
          configMap:
            name: {{ include "skyvault.fullname" . }}-config
        {{- if .Values.development.sourceCodeMount.enabled }}
        - name: source-code
          hostPath:
            path: {{ .Values.development.sourceCodeMount.hostPath }}
            type: Directory
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/skyvault", "--debug" ]
          ports:
            - containerPort: {{ .Values.cache.port }}
              protocol: TCP
          # Use the entire ConfigMap as environment variables
          envFrom:
            - configMapRef:
                name: {{ include "skyvault.fullname" . }}-config
          # Add service-specific environment variables that aren't in the ConfigMap
          env:
            - name: SKYVAULT_ADDR
              value: "0.0.0.0:{{ .Values.cache.port }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/skyvault/config
            {{- if .Values.development.sourceCodeMount.enabled }}
            - name: source-code
              mountPath: /src
            {{- end }}
          livenessProbe:
            grpc:
              port: {{ .Values.cache.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: {{ .Values.cache.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.cache.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 