{{- if .Values.cache.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-cache-{{ .Values.cache.instance }}
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    skyvault.io/instance: {{ .Values.cache.instance }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cache.port }}
      targetPort: {{ .Values.cache.port }}
      protocol: TCP
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
    skyvault.io/instance: {{ .Values.cache.instance }}
{{- end }} 