{{- if .Values.storage.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-minio
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
{{- end }} 