{{- if and .Values.storage.deploy .Values.storage.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skyvault.fullname" . }}-minio
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.minio.persistence.size }}
{{- end }} 