{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyvault.fullname" . }}-orchestrator
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: NodePort
  ports:
    - port: {{ .Values.orchestrator.port }}
      targetPort: {{ .Values.orchestrator.port }}
      protocol: TCP
  selector:
    {{- include "skyvault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
{{- end }} 