{{- if .Values.orchestrator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyvault.fullname" . }}-orchestrator
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicas }}
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      serviceAccountName: {{ include "skyvault.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        # Mount ConfigMap as a volume if needed for file-based configuration
        - name: config-volume
          configMap:
            name: {{ include "skyvault.fullname" . }}-config
        {{- if and .Values.development.enabled .Values.development.sourceCodeMount.enabled }}
        - name: source-code
          hostPath:
            path: {{ .Values.development.sourceCodeMount.hostPath }}
            type: Directory
        {{- end }}
      containers:
        - name: skyvault
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/skyvault", "--debug" ]
          ports:
            - containerPort: {{ .Values.orchestrator.port }}
              protocol: TCP
          # Use the entire ConfigMap as environment variables
          envFrom:
            - configMapRef:
                name: {{ include "skyvault.fullname" . }}-config
          # Add service-specific environment variables that aren't in the ConfigMap
          env:
            - name: SKYVAULT_ADDR
              value: "0.0.0.0:{{ .Values.orchestrator.port }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/skyvault/config
            {{- if and .Values.development.enabled .Values.development.sourceCodeMount.enabled }}
            - name: source-code
              mountPath: /app/src
            {{- end }}
          livenessProbe:
            grpc:
              port: {{ .Values.orchestrator.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: {{ .Values.orchestrator.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
{{- end }} 