name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: SQLc Generate
        run: go tool sqlc generate -f ./internal/database/sqlc.yaml && git diff --exit-code

      - name: Buf Generate
        run: go tool buf generate --template proto/buf.gen.yaml && git diff --exit-code

      - name: Go Format
        run: go fmt ./... && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Staticcheck
        run: go tool staticcheck ./...

      - name: Go Vulncheck
        run: go tool govulncheck

      - name: Go Build
        run: go build ./...

      - name: Go Test
        run: go test -v -count=1 -race -shuffle=on ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      packages: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t ratchet:latest .

      - name: Scan Docker Image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ratchet:latest
          format: "sarif"
          output: trivy-results.sarif
          exit-code: "1"
          ignore-unfixed: true
        continue-on-error: true

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Fail if vulnerabilities found
        if: steps.trivy_scan.outcome == 'failure'
        run: exit 1
